//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiPokemon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pokemon
    {
        public int id { get; set; }
        public string name { get; set; }
        public string img { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public Nullable<int> type1 { get; set; }
        public Nullable<int> type2 { get; set; }
    }
}
